name=R558S
version=1.0.0
author=Nahom Yirga
maintainer=Nahom Yirga
sentence=Arduino library for R558S fingerprint sensors.
paragraph=Provides fingerprint image capture, feature extraction, template creation, storage, identification, deletion, database clearing, LED control, and finger detection for R558S fingerprint modules.
category=Sensors
url=https://github.com/nahomyirga787-spec/R558S
architectures=*
includes=R558S.h

